name: Deploy pygoat
on:
  push:
    branches: [ master ]

jobs:
 conviso:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{secrets.FLOW_API_KEY}}
   steps:
   - uses: actions/checkout@v2
   - name: Run Flow SAST
     run: flow sast run --project-code ${{secrets.FLOW_PROJECT_CODE}} --fail-on-severity-threshold MEDIUM
   - name: Run Flow SCA
     run: flow sca run -v INFO
